app_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Page:index }
    requirements:
        _method:  GET

app_homepage:
  pattern: /hello/{name}
  defaults: {_controller: AppBundle:Default:index}

app_homepage_test:
  pattern: /test/{name}
  defaults: {_controller: AppBundle:MyController:test}