app_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Page:index }
    requirements:
        _method:  GET

app_about:
    pattern:  /about
    defaults: { _controller: AppBundle:Page:about }
    requirements:
        _method:  GET

app_contact:
    pattern:  /contact
    defaults: { _controller: AppBundle:Page:contact }
    requirements:
        _method:  GET|POST


app_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: AppBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

app_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: AppBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+

app_hello:
  pattern: /hello/{name}
  defaults: {_controller: AppBundle:Default:index}

app_test:
  pattern: /test/{name}
  defaults: {_controller: AppBundle:MyController:test}