app_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Page:index }
    requirements:
        _method:  GET

app_about:
    pattern:  /about/
    defaults: { _controller: AppBundle:Page:about }
    requirements:
        _method:  GET

app_hello:
  pattern: /hello/{name}
  defaults: {_controller: AppBundle:Default:index}

app_test:
  pattern: /test/{name}
  defaults: {_controller: AppBundle:MyController:test}