parameters:
#    app.example.class: AppBundle\Example

services:
    blog.twig.extension:
        class: AppBundle\Twig\Extensions\BlogExtension
        tags:
            - { name: twig.extension }

    blog.manager.comment:
        class: AppBundle\Manager\CommentManager
        arguments:
            - @doctrine
            - %commentClass%
